# fly.toml app configuration file generated for ivorypay-restaurants on 2024-02-03T14:18:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ivorypay-restaurants"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
